services:
  ebill-frontend:
    image: tushar26g/ebill-frontend
    container_name: ebill-frontend
    # Keep stdin_open because we don't want this container to exit immediately which it
    # otherwise would have because there's no foreground processes
    stdin_open: true
    ports:
      - "3000:3000"
#    networks:
#      fintrack:
#        ipv4_address: 172.28.1.6
    depends_on:
      - ebill-backend

  ebill-backend:
    image: tushar26g/ebill-backend
    container_name: ebill-backend
    ports:
      - "5000:5000"
#    networks:
#      fintrack:
#        ipv4_address: 172.28.1.7
    environment:
      - MYSQL_HOST=172.16.137.28
      - MYSQL_PORT=3308
    depends_on:
        - mydb
    # Using Docker volume for persisting logs
    # ./backend/logs refers to the path /home/backend/logs on the host machine
    # and we're linking it to logs folder on the container machine where Morgan logger logs its output

  mydb:
    image: mysql:latest
    ports:
      - "3308:3306"
    container_name: database-container
#    networks:
#      fintrack:
#        ipv4_address: 172.28.1.8
    environment:
      - MYSQL_ROOT_PASSWORD=password
#      - MYSQL_DATABASE=EBillDataCenter
    volumes:
      - /var/lib/mysql

